name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you're deploying from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up remote URL for deployment
        run: git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GH_TOKEN }}@github.com/$GITHUB_ACTOR/mySite.git

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Set Git user identity
        run: |
          git config --global user.name "DerrickMullins"
          git config --global user.email "djm2382@gmail.com"

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Provide the token as an environment variable
